"""empty message

Revision ID: 653c8a5b16fb
Revises: 
Create Date: 2018-12-23 19:34:11.435444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653c8a5b16fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('slack', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('name_first', sa.String(length=80), nullable=True),
    sa.Column('name_last', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('slack'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ccy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ccy_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stripeplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ccy_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('acct_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acct_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['ccy_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('ccy_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('recvr_id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ccy_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['recvr_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['requestor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_donation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('card', sa.String(), nullable=False),
    sa.Column('stripe_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=80), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('txs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['txs'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_subscription',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_plan_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('txs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stripe_plan_id'], ['stripeplan.id'], ),
    sa.ForeignKeyConstraint(['txs'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_subscription')
    op.drop_table('stripe_donation')
    op.drop_table('transaction')
    op.drop_table('stripeplan')
    op.drop_table('project')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('currency')
    # ### end Alembic commands ###
